site_name: OpenIndiana Docs (Demo 2.0)
site_favicon: favicon.ico
theme: spacelab
extra:
        theme_inverse: true
pages:
- Home: index.md
- About: about.md
- Contrib: 
        - 'Getting Started': contrib/getting-started.md
        - 'Doc Team Tools' : contrib/tools.md
        - 'Doc Team Style Guide': contrib/style.md
        - 'Doc Team Roles': contrib/roles.md
        - 'Doc Team Topics': contrib/topics.md 
- Dev:
        - 'Userland': dev/userland.md
- FAQ: faq.md
- Handbook: handbook/handbook.md
- Misc:
        - 'Code of Conduct': misc/conduct.md
- Notes:
        - 'The OpenSolaris Redistributable Books': notes/books.md
        - 'Content Management - The BSD Approach': notes/bsd.md
        - 'OpenIndiana Content Creation': notes/content.md
        - 'Improving the OpenIndiana Project': notes/project.md
        - 'GitHub Readme': notes/README.md
        - 'Building a Document Management Toolchain using Sphinx': notes/sphinx.md
        - 'Continuous Integration Content Management': notes/toolchain.md
