site_name: OpenIndiana Docs (Demo 2.0)
pages:
- Home: index.md
- About: about.md
- Notes:
        - 'The OpenSolaris Redistributable Books': notes/books.md
        - 'Content Management - The BSD Approach': notes/bsd.md
        - 'OpenIndiana Content Creation': notes/content.md
        - 'OpenIndiana Handbook': notes/handbook.md
        - 'Improving the OpenIndiana Project': notes/project.md
        - 'GitHub Readme': notes/README.md
        - 'Building a Document Management Toolchain using Sphinx': notes/sphinx.md
        - 'Continuous Integration Content Management': notes/toolchain.md
- Contrib: contrib/index.md
- FAQ: faq.md
- Dev:
        - 'Userland': dev/userland.md
- Misc:
        - 'Code of Conduct': misc/conduct.md

theme: spacelab
extra:
        theme_inverse: true
