site_name: OpenIndiana Docs (Demo 2.0)
site_favicon: favicon.ico
repo_url: https://github.com/makruger/website-2.0
theme: spacelab
google_analytics: ['UA-77447740-2', 'auto']
extra:
        theme_inverse: true
pages:
- Home: index.md

- About: 
        - 'About OpenIndiana Docs': misc/about.md
        - 'Public Documentation License': misc/pdl.md

- Contrib: 
        - 'Getting Started': contrib/getting-started.md
        - 'Contributor Tools' : contrib/tools.md
        - 'Contributor Roles': contrib/roles.md
        - 'Contributor Topics': contrib/topics.md 
        - 'Contributor Style Guide': contrib/style.md
        - 'Markdown Syntax Guide': contrib/markdown.md

- Docs:
        - 'OpenIndiana Code of Conduct': misc/conduct.md
        - 'OpenIndiana FAQ': misc/faq.md
        - 'OpenIndiana Handbook':
                - 'Appendix': handbook/appendix.md
                - 'Handbook (original)': handbook/handbook.md
                - 'Getting Started': handbook/getting-started.md
        - OpenSolaris Books:
                - 'Book Index': books/index.md
                - 'Basic Administration': books/basic.md
                - 'Advanced Administration': books/advanced.md
                - 'Solaris Express Administration': books/express.md
                - 'Trusted Extensions Administration': books/trusted.md
                - 'Development Titles': books/develop.md

        - Development:
                - 'Building oi-userland': dev/userland.md

- Notes:
        - 'OpenIndiana Content Creation': notes/content.md
        - 'Content Management - The BSD Approach': notes/bsd.md
        - 'Improving the OpenIndiana Project': notes/project.md
        - 'The OpenSolaris Redistributable Books': notes/books.md

markdown_extensions:
        - admonition:

copyright: Copyright &copy; 2016 <a href="http://www.openindiana.org">The OpenIndiana Docs Team</a>

