site_name: OpenIndiana Docs (Demo 2.0)
site_favicon: favicon.ico
repo_url: https://github.com/makruger/website-2.0
theme: spacelab
google_analytics: ['UA-77447740-2', 'auto']
extra:
        theme_inverse: true
pages:
- Home: index.md
- About: 
        - 'About OpenIndiana Docs': misc/about.md
        - 'Public Documentation License': misc/pdl.md
- Contrib: 
        - 'Getting Started': contrib/getting-started.md
        - 'Doc Team Tools' : contrib/tools.md
        - 'Doc Team Roles': contrib/roles.md
        - 'Markdown Syntax Guide': contrib/markdown.md
        - 'Doc Team Style Guide': contrib/style.md
- Docs:
        - 'OpenIndiana FAQ': misc/faq.md
        - 'OpenIndiana Handbook': handbook/handbook.md
        - 'Code of Conduct': misc/conduct.md
        - Books:
                - 'OSOL Books': books/index.md
                - 'Basic Administration': books/basic.md
                - 'Advanced Administration': books/advanced.md
                - 'Solaris Express Administration': books/express.md
                - 'Trusted Extensions Administration': books/trusted.md
                - 'Development Titles': books/develop.md
        - Dev:
                - 'Building oi-userland': dev/userland.md
- Notes:
        - 'The OpenSolaris Redistributable Books': notes/books.md
        - 'Content Management - The BSD Approach': notes/bsd.md
        - 'OpenIndiana Content Creation': notes/content.md
        - 'Improving the OpenIndiana Project': notes/project.md
        - 'GitHub Readme': notes/README.md
        - 'Building a Document Management Toolchain using Sphinx': notes/sphinx.md
        - 'Continuous Integration Content Management': notes/toolchain.md
        - 'Topics to write about': notes/topics.md 

markdown_extensions:
        - admonition:

copyright: Copyright &copy; 2016 <a href="http://www.openindiana.org">The OpenIndiana Docs Team</a>

